---
title: "Pre-registered randomized double blinded creatine study on recreational climbers"
author: "Jesper Fischer Ehmsen"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
link-citations: yes
linkcolor: blue
csl: nature.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Abstract
===============================================================================













Methods
===============================================================================




Results
===============================================================================



```{r, include=FALSE, eval = T}
#source("scripts.R")
#data = get_data1()

source("scripts.R")
data = get_data()


m1 = manova(cbind(crimphøjremax,crimpvenstremax, pinchhøjremax, pinchvenstremax,pullups_r,lattice_r,ll_r,lr_r) ~ 
              tid*gruppe+Error(id),
              data = data)


results = summary(m1)

#check for univariate normality.
library(rstatix)
data %>% group_by(tid,gruppe) %>%  shapiro_test(crimphøjremax,crimpvenstremax, pinchhøjremax, pinchvenstremax,pullups_r,lattice_r,ll_r,lr_r)

#multivariate normality using Mardia’s Skewness and Kurtosis test,
library(mvnormalTest)
mardia(data[, c("crimphøjremax", "crimpvenstremax","pinchhøjremax","pinchvenstremax","pullups_r","lattice_r","ll_r","lr_r")])$mv.test

##box m test
library(heplots)
boxM(Y = data[, c("crimphøjremax", "crimpvenstremax","pinchhøjremax","pinchvenstremax","pullups_r","lattice_r","ll_r","lr_r")], group = data$tid)
boxM(Y = data[, c("crimphøjremax", "crimpvenstremax","pinchhøjremax","pinchvenstremax","pullups_r","lattice_r","ll_r","lr_r")], group = data$gruppe)


library(rstatix)
# get distance (outlier test:)
mahalanobis_distance(data = data[, c("crimphøjremax", "crimpvenstremax","pinchhøjremax","pinchvenstremax","pullups_r","lattice_r","ll_r","lr_r")])$is.outlier

#correlation-test to see if some are very correlated
cor.test(x = data$pinchhøjremax, y = data$crimphøjremax, method = "pearson")$estimate
cor.test(x = data$ll_r, y = data$lr_r, method = "pearson")$estimate
cor.test(x = data$lattice_r, y = data$pullups_r, method = "pearson")$estimate

```

From our analysis we found a non-significant group by time interaction effect Pillai = `r round(results$"Error: Within"$stats[2,2],2)`, F = `r round(results$"Error: Within"$stats[2,3],2)` p = `r round(results$"Error: Within"$stats[2,6],2)` 


```{r, fig.width = 6, fig.height = 5, warning = F, message = F, echo = F, fig.cap = "This is the figure caption to make the space fit"}
#plots
library(ggpol)

newdata <- data[order(data$crimphøjremax),]
data$tid = as.factor(data$tid)

data1 = data %>% mutate(tid = as.numeric(as.character(tid))) %>% mutate(tid2 = ifelse(data$tid == 1, a<-1.25, b<-1.75))

data %>% ggplot(aes(x = tid, y = ll_r))+ 
  geom_boxplot(aes(col = gruppe), outlier.color = NA,width = 0.3)+
  geom_line(data = data1, aes(x = tid2, y = ll_r,group = id, col = gruppe),position=position_dodge(0.1), size = 1.1)+
  geom_point(data = data1, aes(x = tid2, y = ll_r, col = gruppe, group = id), position = position_dodge(0.1), size = 2)+
scale_color_manual(labels=c("no-good-stuff","the good stuff"), values = c("#a9a9a9","#000000"))+scale_x_discrete(" ", breaks = c(1,2), labels = c("pre","post"))+ggtitle("group by time of the good stuff in lock-off on left arm")+ylab("Time (s)")+ theme(plot.title = element_text(hjust = 0.5))#+facet_wrap(~kod, labeller = as_labeller(c("0" = "Ingen kød","1" = "Kød!")))
```








Discussion
===============================================================================


