---
title: "Power-simulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sjmisc)
library(lmerTest)
library(ggpubr)
library(simr)
library(MuMIn)
library(car)

```




```{r}

#the real deal
simulations = 1000
pmk = rep(1,simulations)
pmf = rep(1, simulations)
pmkbw = rep(1,simulations)
pmfbw = rep(1, simulations)
pp = rep(1,simulations)
ppbw = rep(1,simulations)
ph= rep(1,simulations)
phmr = rep(1,simulations)
phml = rep(1,simulations)
pll = rep(1,simulations)
plr = rep(1,simulations)
ppir = rep(1,simulations)
ppil = rep(1,simulations)
pbw = rep(1,simulations)
effectsizep = rep(1,simulations)
effectsizepbw = rep(1,simulations)
effectsizehml = rep(1,simulations)
effectsizeh = rep(1,simulations)
effectsizehmr = rep(1,simulations)
effectsizell = rep(1,simulations)
effectsizelr = rep(1,simulations)
effectsizepir = rep(1,simulations)
effectsizepil = rep(1,simulations)
effectsizebw = rep(1,simulations)

sims = function(n){
for (i in seq(simulations)){

simdata2 = data.frame(id = 1:n)
simdata2$time = rep(0, n)
simdata2$treatment = rep("control",n)

simdata3 = data.frame(id = 1:n)
simdata3$time = rep(1, n)
simdata3$treatment = rep("control",n)

simdata4 = data.frame(id = (n+1):(2*n))
simdata4$time = rep(0, n)
simdata4$treatment = rep("creatine",n)

simdata5 = data.frame(id = (n+1):(n*2))
simdata5$time = rep(1, n)
simdata5$treatment = rep("creatine",n)

ll <<- rbind(simdata2, simdata3, simdata4, simdata5)

ll$treatment = as.factor(ll$treatment)
ll$time = as.factor(ll$time)
ll$id = as.factor(ll$id)

#body weight
c0 = rnorm(n, 65, 7.5)
c1 = rnorm(n, c0, 0.5)
t0 = rnorm(n, 65, 7.5)        
t1 = rnorm(n, t0+rnorm(n, 1, 0.7), 0.5)  

u = c(c0,c1,t0,t1)

ll$bw = u

#hang time
c0 = rnorm(n, 20, 5)
c1 = rnorm(n, c0, 1.2)
t0 = rnorm(n, 20, 5)        
t1 = rnorm(n, t0+rnorm(n, 1.2, 0.3), 1.2)  


u = c(c0,c1,t0,t1)

ll$h = u
#ll$he = ll$he*ll$bw

#pull ups
c0 = rnorm(n, 10, 4)
c1 = rnorm(n, c0, 1)
t0 = rnorm(n, 10, 4)        
t1 = rnorm(n, t0+rnorm(n,1,0.3), 1)  

u = c(c0,c1,t0,t1)
ll$p = u
#ll$pe = ll$pe*ll$bw

#max vol. right
c0 = rnorm(n, 400, 150)
c1 = rnorm(n, c0, 25)
t0 = rnorm(n, 400, 150)        
t1 = rnorm(n, t0+rnorm(n, 30, 15), 25)  

u = c(c0,c1,t0,t1)

ll$hmr = u


#max vol. left
c0 = rnorm(n, 400, 150)
c1 = rnorm(n, c0, 25)
t0 = rnorm(n, 400, 150)        
t1 = rnorm(n, t0+rnorm(n, 30, 15), 25)  
  
u = c(c0,c1,t0,t1)

ll$hml = u

#pinch right max
c0 = rnorm(n, 15, 4)
c1 = rnorm(n, c0, 1)
t0 = rnorm(n, 15, 4)        
t1 = rnorm(n, t0+rnorm(n, 1, 0.3), 1)  

u = c(c0,c1,t0,t1)

ll$pir = u

#pinch left max
c0 = rnorm(n, 15, 4)
c1 = rnorm(n, c0, 1)
t0 = rnorm(n, 15, 4)        
t1 = rnorm(n, t0+rnorm(n, 1, 0.3), 1)  

u = c(c0,c1,t0,t1)

ll$pil = u


#lock off left
c0 = rnorm(n, 15, 4)
c1 = rnorm(n, c0, 1)
t0 = rnorm(n, 15, 4)        
t1 = rnorm(n, t0+rnorm(n, 1, 0.3), 1)  

u = c(c0,c1,t0,t1)

ll$ll = u


#lock off right
c0 = rnorm(n, 15, 4)
c1 = rnorm(n, c0, 1)
t0 = rnorm(n, 15, 4)        
t1 = rnorm(n, t0+rnorm(n, 1, 0.3), 1)  

u = c(c0,c1,t0,t1)

ll$lr = u


ll$pbw = ll$p/ll$bw
ll$llbw = ll$ll/ll$bw
ll$lrbw = ll$lr/ll$bw
ll$hbw = ll$h/ll$bw
ll$hmlbw = ll$hml/ll$bw
ll$hmrbw = ll$hmr/ll$bw
ll$pirbw = ll$pir/ll$bw
ll$pilbw = ll$pil/ll$bw


mk = manova(cbind(p, ll, lr) ~ time*treatment+ Error(id), data = ll)

mkbw = manova(cbind(pbw, llbw, lrbw) ~ time*treatment+ Error(id), data = ll)

mf = manova(cbind(h, hmr, hml, pir, pil) ~ time*treatment+ Error(id), data = ll)

mfbw = manova(cbind(hbw, hmrbw, hmlbw, pirbw, pilbw) ~ time*treatment+ Error(id), data = ll)



pmk[i] <<- summary(mk)[2]$`Error: Within`$stats[2,6]
pmf[i]<<- summary(mf)[2]$`Error: Within`$stats[2,6]

pmkbw[i] <<- summary(mkbw)[2]$`Error: Within`$stats[2,6]
pmfbw[i]<<- summary(mfbw)[2]$`Error: Within`$stats[2,6]


mbw = lmer(bw ~ time*treatment+(1|id), data = ll)
pbw[i] <<- summary(mbw)$coefficients[4,5]
aa = data.frame(VarCorr(mbw))
effectsizebw[i] <<- summary(mbw)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])


mp = lmer(p ~ time*treatment+(1|id), data = ll)
pp[i] <<- summary(mp)$coefficients[4,5]
aa = data.frame(VarCorr(mp))
effectsizep[i] <<- summary(mp)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mpbw = lmer(p ~ time*treatment+bw+(1|id), data = ll)
ppbw[i] <<- summary(mpbw)$coefficients[4,5]
aa = data.frame(VarCorr(mpbw))
effectsizepbw[i] <<- summary(mpbw)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])


mh = lmer(h ~ time*treatment+(1|id), data = ll)
ph[i] <<- summary(mh)$coefficients[4,5]
aa = data.frame(VarCorr(mh))
effectsizeh[i] <<- summary(mh)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mhmr = lmer(hmr ~ time*treatment+(1|id), data = ll)
phmr[i] <<- summary(mhmr)$coefficients[4,5]
aa = data.frame(VarCorr(mhmr))
effectsizehmr[i] <<- summary(mhmr)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mhml = lmer(hml ~ time*treatment+(1|id), data = ll)
phml[i] <<- summary(mhml)$coefficients[4,5]
aa = data.frame(VarCorr(mhml))
effectsizehml[i] <<- summary(mhml)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mll = lmer(ll ~ time*treatment+(1|id), data = ll)
pll[i] <<- summary(mll)$coefficients[4,5]
aa = data.frame(VarCorr(mll))
effectsizell[i] <<- summary(mll)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mlr = lmer(ll ~ time*treatment+(1|id), data = ll)
plr[i] <<- summary(mlr)$coefficients[4,5]
aa = data.frame(VarCorr(mlr))
effectsizelr[i] <<- summary(mlr)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mpir = lmer(pir ~ time*treatment+(1|id), data = ll)
ppir[i] <<- summary(mpir)$coefficients[4,5]
aa = data.frame(VarCorr(mpir))
effectsizepir[i] <<- summary(mpir)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])

mpil = lmer(pil ~ time*treatment+(1|id), data = ll)
ppil[i] <<- summary(mpil)$coefficients[4,5]
aa = data.frame(VarCorr(mpil))
effectsizepil[i] <<- summary(mpil)$coefficients[4,1]/sqrt(aa[1,4]+aa[2,4])


}
}

sims(20)
```


```{r}
o = data.frame(effectsizeh, effectsizehml, effectsizehmr, effectsizell, effectsizelr, effectsizep, effectsizepil, effectsizepir, effectsizebw)

f = function(x){
  list(mean(x),sd(x))
}


v = data.frame(sapply(o, f))



oo = data.frame(ph,phml,phmr,pll,plr,pp,ppil,ppir,pbw)
oof = data.frame(pmk, pmkbw, pmf, pmfbw, pp, ppbw)

for (i in (1:9)){
oo[,i] = ifelse(oo[,i]<0.05, 1,0)  
}

apply(oo, 2, sum)

for (i in (1:6)){
oof[,i] = ifelse(oof[,i]<0.05, 1,0)  
}
apply(oof, 2, sum)


```


```{r}
ppe2000 = ppe
phml2000 = phml
effectsizehml2000 = effectsizehml
effectsizepe2000 = effectsizepe


a = rep(1,6)
b = rep(1,6)
c = rep(1,6)
d = rep(1,6)
e = rep(1,6)
f = rep(1,6)
g = rep(1,6)
h = rep(1,6)
q = rep(1,6)
j = rep(1,6)
l = rep(1,6)
v  = rep(1,6)
q = rep(1,6)
y  = rep(1,6)



draw_for_all2 = function(n1,n2,n3,n4,n5,n6){
for (i in c(n1,n2,n3,n4,n5,n6)){
sims(i)
mk1 <- pmk
data.frame(assign(paste("mk",i,sep = ""), mk1))
mf1 <- pmf
assign(paste("mf",i,sep = ""), mf1)

mk1bw <- pmkbw
data.frame(assign(paste("mkbw",i,sep = ""), mk1bw))
mf1bw <- pmfbw
assign(paste("mfbw",i,sep = ""), mf1bw)
p1 = pp
assign(paste("p",i,sep = ""), p1)
h1 = ph
assign(paste("h",i,sep = ""), h1)
hmr1 = phmr
assign(paste("hmr",i,sep = ""), hmr1)
hml1 = phml
assign(paste("hml",i,sep = ""), hml1)
ll1 = pll
assign(paste("ll",i,sep = ""), ll1)
lr1 = plr
assign(paste("lr",i,sep = ""), lr1)
pir1 = ppir
assign(paste("pir",i,sep = ""), pir1)
pil1 = ppil
assign(paste("pil",i,sep = ""), pil1)
}

mk1 <- data.frame(mk5)
mf1 <- data.frame(mf5)
mkbw1 <- data.frame(mkbw5)
mfbw1 <- data.frame(mfbw5)
p1 <- data.frame(p5)
h1 <- data.frame(h5)
hmr1 <- data.frame(hmr5)
hml1 <- data.frame(hml5)
ll1 <- data.frame(ll5)
lr1 <- data.frame(lr5)
pir1 <- data.frame(pir5)
pil1 <- data.frame(pil5)


mk <<- cbind(mk1,mk10,mk15,mk20,mk25,mk30)
mf <<- cbind(mf1,mf10,mf15,mf20,mf25,mf30)
mkbw <<- cbind(mkbw1,mkbw10,mkbw15,mkbw20,mkbw25,mkbw30)
mfbw <<- cbind(mfbw1,mfbw10,mfbw15,mfbw20,mfbw25,mfbw30)
p <<- cbind(p1,p10,p15,p20,p25,p30)
h <<- cbind(h1,h10,h15,h20,h25,h30)
hmr <<- cbind(hmr1,hmr10,hmr15,hmr20,hmr25,hmr30)
hml <<- cbind(hml1,hml10,hml15,hml20,hml25,hml30)
lr <<- cbind(lr1,lr10,lr15,lr20,lr25,lr30)
ll <<- cbind(ll1,ll10,ll15,ll20,ll25,ll30)
pir <<- cbind(pir1,pir10,pir15,pir20,pir25,pir30)
pil <<- cbind(pil1,pil10,pil15,pil20,pil25,pil30)


mkt <- data.frame(t(mk))
mft <- data.frame(t(mf))
mkbwt <- data.frame(t(mkbw))
mfbwt <- data.frame(t(mfbw))
pt <- data.frame(t(p))
ht <- data.frame(t(h))
hmrt <- data.frame(t(hmr))
hmlt <- data.frame(t(hml))
llt <- data.frame(t(ll))
lrt <- data.frame(t(lr))
pirt <- data.frame(t(pir))
pilt <- data.frame(t(pil))




for(i in 1:6){
  mkt[i,] = ifelse(mkt[i,]<0.05,1,0)
  mft[i,] = ifelse(mft[i,]<0.05,1,0)
  mkbwt[i,] = ifelse(mkbwt[i,]<0.05,1,0)
  mfbwt[i,] = ifelse(mfbwt[i,]<0.05,1,0)
  pt[i,] = ifelse(pt[i,]<0.00625,1,0)
  ht[i,] = ifelse(ht[i,]<0.008333333,1,0)
  hmrt[i,] = ifelse(hmrt[i,]<0.01,1,0)
  hmlt[i,] = ifelse(hmlt[i,]<0.0125,1,0)
  llt[i,] = ifelse(llt[i,]<0.01666667,1,0)
  lrt[i,] = ifelse(lrt[i,]<0.01666667,1,0)
  pirt[i,] = ifelse(pirt[i,]<0.025,1,0)
  pilt[i,] = ifelse(pilt[i,]<0.05,1,0)
}



for (i in 1:6){
a[i] <- sum(mkt[i,])
b[i] <- sum(mft[i,])
c[i] <- sum(pt[i,])
e[i] <- sum(ht[i,])
f[i] <- sum(hmrt[i,])
g[i] <- sum(hmlt[i,])
v[i] <- sum(llt[i,])
d[i] <- sum(lrt[i,])
j[i] <- sum(pirt[i,])
l[i] <- sum(pilt[i,])
q[i] <- sum(mkbwt[i,])
y[i] <- sum(mfbwt[i,])

}

a <- data.frame(a)
b <- data.frame(b)
c <- data.frame(c)
d <- data.frame(d)
e <- data.frame(e)
f <- data.frame(f)
g <- data.frame(g)
v <- data.frame(v)
q <- data.frame(q)
j <- data.frame(j)
l <- data.frame(l)
q <- data.frame(q)
y <- data.frame(y)



a$n = seq(from = 5, to = 30, by = 5)
b$n = seq(from = 5, to = 30, by = 5)
c$n = seq(from = 5, to = 30, by = 5)
d$n = seq(from = 5, to = 30, by = 5)
e$n = seq(from = 5, to = 30, by = 5)
f$n = seq(from = 5, to = 30, by = 5)
g$n = seq(from = 5, to = 30, by = 5)
v$n = seq(from = 5, to = 30, by = 5)
q$n = seq(from = 5, to = 30, by = 5)
j$n = seq(from = 5, to = 30, by = 5)
l$n = seq(from = 5, to = 30, by = 5)
q$n = seq(from = 5, to = 30, by = 5)
y$n = seq(from = 5, to = 30, by = 5)



plotmk <<- ggplot(a, aes(n, a))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for manova krops")
plotmf <<- ggplot(b, aes(n, b))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for manova finger")

plotmkbw <<- ggplot(q, aes(n, q))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for manova krops (bw)")
plotmfbw <<- ggplot(y, aes(n, y))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for manova finger (bw)")

plotp <<- ggplot(c, aes(n, c))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for pull up enduance")
ploth <<- ggplot(e, aes(n, e))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for hang enduance")
plothmr <<- ggplot(f, aes(n, f))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for max hang strength right")
plothml <<- ggplot(g, aes(n, g))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for max hang strength left")
plotll <<- ggplot(v, aes(n, v))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for lock off left strength")
plotlr <<- ggplot(d, aes(n, d))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("power for lock off right strength")
plotpir <<- ggplot(j, aes(n, j))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("pinch right")
plotpil <<- ggplot(l, aes(n, l))+ geom_point()+ylab("number of null hypothese rejected")+xlab("number of participants in each group")+geom_hline(yintercept = simulations*0.8)+ggtitle("pinch left")
}

draw_for_all2(5,10,15,20,25,30)

plotmkbw
plotmfbw
plotmk
plotmf
plotp
ploth
plothmr
plothml
plotll
plotlr
plotpir
plotpil

```

